version: '3.3'

services:

  nginx:
    image: nginx:1.15.8-alpine
    container_name: ra-nginx
    ports:
      - 7070:80
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template
      - ./web:/var/www/html
      - ./nginx/logs:/var/log/nginx
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always

  php:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    container_name: ra-php
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web:/var/www/html
    restart: always

  mysqldb:
    image: mysql:5.7.22
    container_name: ra-db
    ports:
      - 8989:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./etc/db:/var/lib/mysql
    restart: always




